# Generated by Django 4.2 on 2025-09-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aivc_app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The testimonial content')),
                ('author', models.CharField(help_text='Name or designation of the person', max_length=150)),
                ('css_class', models.CharField(blank=True, help_text='Optional CSS class for styling (e.g., leader-card-1, leader-card-2)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
